### ISSUE TITLE
+spelldmg was increased in patch 1.04

### ISSUE THREAD

**Issue by pieterkockx** [elysium-project/database#21]
> +Spell damage and +Healing effects have been increased in effectiveness to make them more attractive to players.

_source: http://wowwiki.wikia.com/wiki/Patch_1.4.0#Items_

The _Band of the Unicorn_ was one of the items in question so I did
`git grep -i 'band of the unicorn'` through the repo and the only reference to this item is in the file _1.05_pve_items.sql_

```
-- SPELLS CHANGED: Band of the Unicorn (ilevel 48 entry 7553). 1 versions
-- Source: http://www.thottbot.com/?n=149426 / http://wow.allakhazam.com/db/price.html?witem=7553
-- * Modified spell 1
-- 1.12 spell 9342 (Increases damage and healing done by magical spells and effects by up to 13.)
-- 1.04 spell 9397 (Increases damage and healing done by magical spells and effects by up to 7.)
UPDATE item_template SET `spellid_1`=9397 WHERE entry=7553;
```

Note that this SQL command _downgrades_ the item since the database contains the items as they were in patch 1.12.

I think the 1.04 means "the oldest reference to this item the author could find", but this appears to be wrong since it was precisely in patch 1.04 that this item, amongst others, received the above mentioned boost.

(See for example these two spreadsheets listing warlock gear:

- patch 1.03
https://docs.google.com/spreadsheets/d/1XufUpGSKHrmlDq3VCQMBDap7gjNk47MS-XILyj3bVaA/edit#gid=118447046

- patch 1.05
https://docs.google.com/spreadsheets/d/125985SX41s1sqW0C6mHGnFS3O7pmxBEY7v2CMA91Hrw/edit#gid=118447046

)

Anyway,
we can extrapolate from this one particular case since most entries are accompanied by a similarly structured comment.

Now I can of course submit a patch for _1.05_pve_items.sql_ but it looks like the repo is currently undergoing a big overhaul so I might want to wait.

Thoughts?

**Comment by Xentr0** [comment]
At least if this is true, a whole bunch of items will be affected, not only band of the unicorn but for example shadoweave set and umbral crystal to mind (having played a lock myself).

**Comment by pieterkockx** [comment]
@thepparker _Downgrade 1.7 → 1.5.sql_ now doesn't contain _Band of the Unicorn_, is this a coincidence or did you read this post? Anyhow, as @Xentr0 mentioned, there are more items, like the Shadoweave set, that were updated in patch 1.04. Let me know if you need any assistance!

**Comment by thepparker** [comment]
The 1.7 database will already have the upgraded stats for those items, as such there's no need to specifically modify them when downgrading 1.7 -> 1.5

**Comment by Xentr0** [comment]
We get that that's how it works, however that's not what happened when the patch was applied on Elysium. Band of the Unicorn has +7 spelldmg in the current Elysium (1.5) version, while it should have +13 spelldmg in 1.5. This is one of many items not correctly updated when patch 1.5 was applied.

**Comment by pieterkockx** [comment]
I agree @thepparker 
But _Downgrade 1.7 → 1.5.sql_ does modify e.g. Shadoweave

**Comment by thepparker** [comment]
The current state of Elysium is not really representative of this repository at the moment @Xentr0. The patch that was applied had a few issues and was reverted, so we're in a temporary limbo state just to have some of 1.5 (i.e. MC items/AV) available.

The issue with some items (such as Shadoweave) is that the only snapshots we have of them are across multiple patches, so we can't say for certain which patch the change occurred in. For Shadoweave specifically, the earlier snapshot is Feb 19, and the next is Nov 13. This leads me to think it was in fact updated in 1.7 rather than 1.4 or 1.5. If you know of other resources which can prove that the change occurred in the earlier patches, I'm more than happy to work it in.

**Comment by Xentr0** [comment]
@thepparker I didn't realise the github patch and the Elysium were out of sync. @pieterkockx already pointed this out to me on voice chat as well. About shadoweave, I'm very certain that on nostalrius at least they updated it in 1.4/1.5 because I was levelling my warlock in that specific patch and it had the stats as shown on db.vanillagaming.org. I only learned about the lower stats while leveling my lock on here pre 1.4-1.5. I stopped playing on nost before ZG hit, so as I said, at least on nost it was updated before 1.7.

**Comment by pieterkockx** [comment]
@thepparker 
In my original post I tried to summarize the reasons I think these spells were updated in 1.04
The spreadsheets I linked there I found in this warlock guide for Nostalrius:
https://legacy-wow.com/warlock-leveling-guide-1-60

In my opinion, the most conclusive evidence is in the patch notes for 1.04 where Blizzard mentions boosting the +spelldmg bonus of many items (unfortunately not further specified):
http://wowwiki.wikia.com/wiki/Patch_1.4.0#Items

I didn't find any mention of similar changes in later patch notes.
